config/routes.rb
Rails.application.routes.draw do
  root 'parks#index'
  devise_for :users

  resources :parks do
    resources :reviews, except: [:edit]
  end
  resources :reviews

  namespace :api do
    namespace :v1 do
      resources :parks, except: [:destroy] do
        resources :reviews
      end
      resources :reviews
      resources :review_upvotes, only: [:create, :edit]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  STATES =
  [
    'AL', 'AK', 'AS', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FM', 'FL', 'GA', 'GU', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS',
    'KY', 'LA', 'ME', 'MH', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'MP',
    'OH', 'OK', 'OR', 'PW', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VI', 'VA', 'WA', 'WV', 'WI', 'WY'
  ]

  def admin?
    role == "Admin"
  end

  validates :name, :address, :city, :state, :zip, presence: true
  validates :zip, length: {is: 5}
  validates :state, inclusion: { in: STATES }

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, numericality: { minimum: 0, maximuim: 5}
  validates :body, presence: true

  belongs_to :user
  belongs_to :park
  has_many :review_upvotes

  def upvote_total
    upvote_total = 0
    self.review_upvotes.each do |vote|
      upvote_total += 1 if vote.value === 1
    end
    upvote_total
  end

  def downvote_total
    downvote_total = 0
    self.review_upvotes.each do |vote|
      downvote_total += 1 if vote.value === -1
    end
    downvote_total
  end
end

app/models/review_upvote.rb
class ReviewUpvote < ApplicationRecord
  belongs_to :user
  belongs_to :review
  validates :value,
    presence: true,
    numericality: {less_than_or_equal_to: 1, greater_than_or_equal_to: -1 }
  validates :user, uniqueness: { scope: :review}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
   role === "admin"
  end

  has_many :reviews
  has_many :review_upvotes
  mount_uploader :profile_photo, ProfilePhotoUploader
end

app/controllers/api/v1/parks_controller.rb
class Api::V1::ParksController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  def index
      render json: {parks: Park.all }
  end

  def show
      render json: { park: Park.find(params[:id]) }
  end

  def create
    park = Park.new(name: params["name"], address: params["address"], city: params["city"], state: params["state"], zip: params["zip"], description: params["description"])
    if park.save
        render json: { park: park, errors: [], successStatus: "Submitted Successfully!"}
    else
        render json: { park: {}, errors: park.errors.full_messages, successStatus: "" }
    end
  end

  def edit
  end

  def update
    park = Park.find(params[:id])
    if park.update(park_params)
      render json: {park: park, errors: ''}
    else
      render json: {errors: park.errors}, status: 422
    end
  end

  private

  def park_params
    params.require(:park).permit(:name, :address, :city, :state, :zip, :description)
  end
end

app/controllers/api/v1/review_upvotes_controller.rb
class Api::V1::ReviewUpvotesController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  def create
    if current_user.nil?
      render json: {errors: "You need to be logged in to vote!"}
    else
      review_upvote = ReviewUpvote.find_by(
        user_id: review_upvotes_params[:user][:id],
        review_id: review_upvotes_params[:review_id]
      )
      if review_upvote && review_upvote[:value] == review_upvotes_params[:value]
        review_upvote[:value] = 0
        review_upvote.save
      elsif review_upvote
        review_upvote[:value] = review_upvotes_params[:value]
        review_upvote.save
      else
        ReviewUpvote.create!(
          user: review_upvotes_params[:user],
          review_id: review_upvotes_params[:review_id],
          value: review_upvotes_params[:value]
        )
      end
      render json: {
        upvote_total: Review.find(review_upvotes_params[:review_id]).upvote_total,
        downvote_total: Review.find(review_upvotes_params[:review_id]).downvote_total,
        errors: []
      }
    end
  end

  private

  def review_upvotes_params
    output = params.require(:review_upvote).permit(:review_id, :value)
    output[:user] = current_user
    output
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def index
    reviews = Park.find(params[:park_id]).reviews

    reviews_users = reviews.map do |review|
      review.user.email
    end

    formatted_reviews = []
    reviews.each_with_index do |val, index|
      upvote_values = val.review_upvotes.map { |upvote| upvote.value }
      upvote_total = 0
      downvote_total = 0
      upvote_values.each do |val|
        upvote_total += 1 if val === 1
        downvote_total +=1 if val === -1
      end
      formatted_reviews.push(
        {
          review_data: val,
          user_data: reviews_users[index],
          upvote_total: upvote_total,
          downvote_total: downvote_total
        }
      )
    end

    render json: { formatted_reviews: formatted_reviews, formatted_user: current_user }
  end

  def show
    render json: { review: Review.find(params[:id]), formatted_user: current_user }
  end

  def create
    review = Review.new(review_params)
    review.user = current_user
    if review.save
      render json: { review: review, errors: [] }
    else
      render json: { review: {}, errors: review.errors.full_messages }
    end
  end

  def edit
    render json: { review: Review.find(params[:id]), errors: ''  }
  end

  def update
    review = Review.find(params[:id])
    if review.update(review_params)
      render json: {review: review}

    else
      render json: {errors: review.errors}, status: 422
    end
  end

  def destroy
    review = Review.find(params[:id])

    if review.destroy
      reviews = review.park.reviews
      render json: { reviews: reviews, errors: [] }
    else
      reviews = review.park.reviews
      render json: { reviews: reviews, errors: review.errors}
    end

  end

  private

  def review_params
    params.require(:review).permit(:park_id, :rating, :body)
  end

  def authorize_admin
    if !current_user.admin?
      flash[:notice] = "You Do not have access to this page"
      redirect_to parks_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_photo])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :authorize_user, except: [:index, :show, :new, :edit, :create]
  before_action :authorize_admin, except: [:index, :show, :edit, :new, :create, :destroy]
  def index
    @parks = Park.all
  end

  def show
    @park = Park.find(params[:id])
  end

  def edit
    @park = Park.find(params[:id])
  end

  def update

  end

  def destroy
    @park = Park.find(params[:id])
    @park.destroy
    redirect_to parks_path
  end

  private
  def authorize_user
    if !user_signed_in? || !current_user.admin?
      flash[:notice] = "You Do not have access to this page"
      redirect_to parks_path
    end
  end
  def authorize_admin
    if !current_user.admin?
      flash[:notice] = "You Do not have access to this page"
      redirect_to parks_path
    end
  end
end

app/controllers/review_upvotes_controller.rb
class ReviewUpvotes < ApplicationController

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  end

  def edit
    @review = Review.find(params[:id])
  end


end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParkReviews</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">ParkReviews</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
        <img class="nav-profile-photo" src="<%= current_user.profile_photo %>"/>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/parks/edit.html.erb
<div id="app">
</div>

app/views/parks/index.html.erb
<h1 class="index-title"> Parks </h1>
<ul>
  <% if user_signed_in? %>
    <button className="button park-button"><%= link_to 'Add a New Park!', new_park_path, class: 'park-button'%> </button><br>
  <% end %>
  <% @parks.each do |park| %>
    <li class="park-index">
      <h2><%= link_to park.name, park_path(park)  %> </h2>
      <h4><%= park.city %>, <%= park.state %> </h4>
    <% if user_signed_in? && !current_user.admin? %>
      <button className="button park-button"><%= link_to "Edit", edit_park_path(park.id), class: 'park-button'%></button>
    <% elsif user_signed_in? && current_user.admin? %>
      <button className="button park-button"><%= link_to "Edit", edit_park_path(park.id), class: 'park-button'%></button>
      <button className="button park-button"><%= link_to "Delete", park_path(park.id), method:
          :delete, data: { confirm: "Are you sure?  This will delete all the associated reviews too!" }, class: 'park-button'%></button>
    <% end %>
    </li>
  <% end %>
</ul>

<div id="app">
</div>

app/views/parks/new.html.erb
<div id="app">
</div>

app/views/reviews/edit.html.erb
<div id="app" />

app/views/reviews/new.html.erb
<div id ="app" />

app/views/reviews/show.html.erb
<div id="app" />

app/views/static_pages/index.html.erb
<div id="app">
</div>